export const users = [
  {
    name: "John Doe",
    phone_number: "555-1234",
    address: "123 Elm Street, Springfield, IL",
    parcel_delivery_time: "10:00 AM",
    parcel_delivery_date: "2024-07-25",
    extra_notes: "Leave package at the front door.",
  },
  {
    name: "Jane Smith",
    phone_number: "555-5678",
    address: "456 Oak Avenue, Metropolis, NY",
    parcel_delivery_time: "2:00 PM",
    parcel_delivery_date: "2024-07-26",
    extra_notes: "Ring the doorbell upon arrival.",
  },
  {
    name: "Alice Johnson",
    phone_number: "555-8765",
    address: "789 Pine Road, Gotham, NJ",
    parcel_delivery_time: "4:00 PM",
    parcel_delivery_date: "2024-07-27",
    extra_notes: "Please call before arriving.",
  },
  {
    name: "John Doe",
    phone_number: "555-1234",
    address: "123 Elm Street, Springfield, IL",
    parcel_delivery_time: "10:00 AM",
    parcel_delivery_date: "2024-07-25",
    extra_notes: "Leave package at the front door.",
  },
  {
    name: "Jane Smith",
    phone_number: "555-5678",
    address: "456 Oak Avenue, Metropolis, NY",
    parcel_delivery_time: "2:00 PM",
    parcel_delivery_date: "2024-07-26",
    extra_notes: "Ring the doorbell upon arrival.",
  },
  {
    name: "Alice Johnson",
    phone_number: "555-8765",
    address: "789 Pine Road, Gotham, NJ",
    parcel_delivery_time: "4:00 PM",
    parcel_delivery_date: "2024-07-27",
    extra_notes: "Please call before arriving.",
  },
];
